var NowPos = 'menu'
var logo = new Image();
logo.src = 'Logo.PNG';
var G_skin = new Image();
G_skin='skin\\'+defaultSkinSettings+'\\G_skin.PNG';
var I_skin = new Image();
I_skin='skin\\'+defaultSkinSettings+'\\I_skin.PNG';
var J_skin = new Image();
J_skin='skin\\'+defaultSkinSettings+'\\J_skin.PNG';
var L_skin = new Image();
L_skin='skin\\'+defaultSkinSettings+'\\L_skin.PNG';
var O_skin = new Image();
O_skin='skin\\'+defaultSkinSettings+'\\O_skin.PNG';
var S_skin = new Image();
S_skin='skin\\'+defaultSkinSettings+'\\S_skin.PNG';
var T_skin = new Image();
T_skin='skin\\'+defaultSkinSettings+'\\T_skin.PNG';
var Z_skin = new Image();
Z_skin='skin\\'+defaultSkinSettings+'\\Z_skin.PNG';